<?php

/**
 * This is the model base class for the table "estado".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Estado".
 *
 * Columns in table "estado" available as properties of the model,
 * followed by relations of table "estado" available as properties of the model.
 *
 * @property integer $id_estado
 * @property string $nome
 * @property string $uf
 * @property integer $id_pais
 *
 * @property Cidade[] $cidades
 * @property Pais $idPais
 */
abstract class BaseEstado extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'estado';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Estado|Estados', $n);
	}

	public static function representingColumn() {
		return 'nome';
	}

	public function rules() {
		return array(
			array('id_pais', 'numerical', 'integerOnly'=>true),
			array('nome', 'length', 'max'=>255),
			array('uf', 'length', 'max'=>5),
			array('nome, uf, id_pais', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_estado, nome, uf, id_pais', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cidades' => array(self::HAS_MANY, 'Cidade', 'id_estado'),
			'idPais' => array(self::BELONGS_TO, 'Pais', 'id_pais'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_estado' => Yii::t('app', 'Id Estado'),
			'nome' => Yii::t('app', 'Nome'),
			'uf' => Yii::t('app', 'Uf'),
			'id_pais' => null,
			'cidades' => null,
			'idPais' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_estado', $this->id_estado);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('uf', $this->uf, true);
		$criteria->compare('id_pais', $this->id_pais);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}