<?php

/**
 * This is the model base class for the table "endereco".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Endereco".
 *
 * Columns in table "endereco" available as properties of the model,
 * followed by relations of table "endereco" available as properties of the model.
 *
 * @property integer $id_endereco
 * @property string $nome
 * @property string $cep
 * @property integer $tipo
 * @property string $rua
 * @property string $numero
 * @property string $complemento
 * @property string $descricao
 * @property string $bairro
 * @property integer $id_pessoa
 * @property integer $id_cidade
 *
 * @property Pessoa $idPessoa
 * @property Cidade $idCidade
 */
abstract class BaseEndereco extends GxActiveRecord {

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'endereco';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'Endereco|Enderecos', $n);
    }

    public static function representingColumn() {
        return 'cep';
    }

    public function rules() {
        return array(
            array('cep, rua, numero, bairro, id_pessoa, id_cidade', 'required'),
            array('tipo, id_pessoa, id_cidade', 'numerical', 'integerOnly' => true),
            array('nome, rua, bairro', 'length', 'max' => 120),
            array('cep', 'length', 'max' => 9),
            array('numero, complemento', 'length', 'max' => 6),
            array('descricao', 'safe'),
            array('nome, tipo, complemento, descricao', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_endereco, nome, cep, tipo, rua, numero, complemento, descricao, bairro, id_pessoa, id_cidade', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
            'idPessoa' => array(self::BELONGS_TO, 'Pessoa', 'id_pessoa'),
            'idCidade' => array(self::BELONGS_TO, 'Cidade', 'id_cidade'),
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'id_endereco' => Yii::t('app', 'Id Endereco'),
            'nome' => Yii::t('app', 'Nome'),
            'cep' => Yii::t('app', 'CEP'),
            'tipo' => Yii::t('app', 'Tipo'),
            'rua' => Yii::t('app', 'Rua'),
            'numero' => Yii::t('app', 'Número'),
            'complemento' => Yii::t('app', 'Complemento'),
            'descricao' => Yii::t('app', 'Descrição'),
            'bairro' => Yii::t('app', 'Bairro'),
            'id_pessoa' => null,
            'id_cidade' => null,
            'idPessoa' => null,
            'idCidade' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_endereco', $this->id_endereco);
        $criteria->compare('nome', $this->nome, true);
        $criteria->compare('cep', $this->cep, true);
        $criteria->compare('tipo', $this->tipo);
        $criteria->compare('rua', $this->rua, true);
        $criteria->compare('numero', $this->numero, true);
        $criteria->compare('complemento', $this->complemento, true);
        $criteria->compare('descricao', $this->descricao, true);
        $criteria->compare('bairro', $this->bairro, true);
        $criteria->compare('id_pessoa', $this->id_pessoa);
        $criteria->compare('id_cidade', $this->id_cidade);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function getTipo($tipo = false) {
        if (!is_numeric($tipo)) {
            $tipo = $this->tipo;
        }
        
        switch ($tipo) {
            case 0: return 'Casa';
            case 1: return 'Apartamento';
            case 2: return 'Comercial';
        }
    }
    
    public function getCidade() {
        return $this->idCidade . ', ' . $this->idCidade->idEstado->uf . ' - ' . $this->idCidade->idEstado->idPais;
    }
}