<?php

/**
 * This is the model base class for the table "pais".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Pais".
 *
 * Columns in table "pais" available as properties of the model,
 * followed by relations of table "pais" available as properties of the model.
 *
 * @property integer $id_pais
 * @property string $nome
 *
 * @property Estado[] $estados
 */
abstract class BasePais extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'pais';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Pais|Paises', $n);
	}

	public static function representingColumn() {
		return 'nome';
	}

	public function rules() {
		return array(
			array('nome', 'length', 'max'=>255),
			array('nome', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_pais, nome', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'estados' => array(self::HAS_MANY, 'Estado', 'id_pais'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_pais' => Yii::t('app', 'Id Pais'),
			'nome' => Yii::t('app', 'Nome'),
			'estados' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_pais', $this->id_pais);
		$criteria->compare('nome', $this->nome, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}