<?php

/**
 * This is the model base class for the table "status".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Status".
 *
 * Columns in table "status" available as properties of the model,
 * followed by relations of table "status" available as properties of the model.
 *
 * @property integer $id_status
 * @property string $nome
 *
 * @property Consulta[] $consultas
 * @property Pagamento[] $pagamentos
 * @property Parcela[] $parcelas
 */
abstract class BaseStatus extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'status';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Status|Statuses', $n);
	}

	public static function representingColumn() {
		return 'nome';
	}

	public function rules() {
		return array(
			array('nome', 'required'),
			array('nome', 'length', 'max'=>45),
			array('id_status, nome', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'consultas' => array(self::HAS_MANY, 'Consulta', 'id_status'),
			'pagamentos' => array(self::HAS_MANY, 'Pagamento', 'id_status'),
			'parcelas' => array(self::HAS_MANY, 'Parcela', 'id_status'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_status' => Yii::t('app', 'Id Status'),
			'nome' => Yii::t('app', 'Nome'),
			'consultas' => null,
			'pagamentos' => null,
			'parcelas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_status', $this->id_status);
		$criteria->compare('nome', $this->nome, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}