<?php

/**
 * This is the model base class for the table "cliente_has_procedimento_has_consulta".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ClienteHasProcedimentoHasConsulta".
 *
 * Columns in table "cliente_has_procedimento_has_consulta" available as properties of the model,
 * followed by relations of table "cliente_has_procedimento_has_consulta" available as properties of the model.
 *
 * @property integer $id_cliente_has_procedimento_has_consulta
 * @property integer $id_cliente_has_procedimento
 * @property integer $id_consulta
 *
 * @property ClienteHasProcedimento $idClienteHasProcedimento
 * @property Consulta $idConsulta
 */
abstract class BaseClienteHasProcedimentoHasConsulta extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cliente_has_procedimento_has_consulta';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ClienteHasProcedimentoHasConsulta|ClienteHasProcedimentoHasConsultas', $n);
	}

	public static function representingColumn() {
		return 'id_cliente_has_procedimento_has_consulta';
	}

	public function rules() {
		return array(
			array('id_cliente_has_procedimento, id_consulta', 'required'),
			array('id_cliente_has_procedimento, id_consulta', 'numerical', 'integerOnly'=>true),
			array('id_cliente_has_procedimento_has_consulta, id_cliente_has_procedimento, id_consulta', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idClienteHasProcedimento' => array(self::BELONGS_TO, 'ClienteHasProcedimento', 'id_cliente_has_procedimento'),
			'idConsulta' => array(self::BELONGS_TO, 'Consulta', 'id_consulta'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_cliente_has_procedimento_has_consulta' => Yii::t('app', 'Id Cliente Has Procedimento Has Consulta'),
			'id_cliente_has_procedimento' => null,
			'id_consulta' => null,
			'idClienteHasProcedimento' => null,
			'idConsulta' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_cliente_has_procedimento_has_consulta', $this->id_cliente_has_procedimento_has_consulta);
		$criteria->compare('id_cliente_has_procedimento', $this->id_cliente_has_procedimento);
		$criteria->compare('id_consulta', $this->id_consulta);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}