<?php

/**
 * This is the model base class for the table "atestado".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Atestado".
 *
 * Columns in table "atestado" available as properties of the model,
 * followed by relations of table "atestado" available as properties of the model.
 *
 * @property integer $id_atestado
 * @property integer $id_consulta
 * @property string $atestado
 *
 * @property Consulta $idConsulta
 */
abstract class BaseAtestado extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'atestado';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Atestado|Atestados', $n);
	}

	public static function representingColumn() {
		return 'atestado';
	}

	public function rules() {
		return array(
			array('id_consulta, atestado', 'required'),
			array('id_consulta', 'numerical', 'integerOnly'=>true),
			array('id_atestado, id_consulta, atestado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idConsulta' => array(self::BELONGS_TO, 'Consulta', 'id_consulta'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_atestado' => Yii::t('app', 'Id Atestado'),
			'id_consulta' => null,
			'atestado' => Yii::t('app', 'Atestado'),
			'idConsulta' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_atestado', $this->id_atestado);
		$criteria->compare('id_consulta', $this->id_consulta);
		$criteria->compare('atestado', $this->atestado, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}