<?php

/**
 * This is the model base class for the table "cliente".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Cliente".
 *
 * Columns in table "cliente" available as properties of the model,
 * followed by relations of table "cliente" available as properties of the model.
 *
 * @property integer $id_cliente
 * @property integer $id_pessoa
 * @property string $data_criacao
 *
 * @property Pessoa $idPessoa
 * @property Consulta[] $consultas
 */
abstract class BaseCliente extends GxActiveRecord {

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'cliente';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'Cliente|Clientes', $n);
    }

    public static function representingColumn() {
        return 'idPessoa';
    }

    public function rules() {
        return array(
            array('id_pessoa, data_criacao', 'required'),
            array('id_pessoa', 'numerical', 'integerOnly' => true),
            array('id_cliente, id_pessoa, data_criacao', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
            'idPessoa' => array(self::BELONGS_TO, 'Pessoa', 'id_pessoa'),
            'consultas' => array(self::HAS_MANY, 'Consulta', 'id_cliente'),
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'id_cliente' => Yii::t('app', 'Id Cliente'),
            'id_pessoa' => null,
            'data_criacao' => Yii::t('app', 'Data Criacao'),
            'idPessoa' => null,
            'consultas' => null,
        );
    }
    
    public function search() {
        $criteria = new CDbCriteria;
        
        $criteria->compare('id_cliente', $this->id_cliente);
        $criteria->compare('id_pessoa', $this->id_pessoa);
        $criteria->compare('data_criacao', $this->data_criacao, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}