<?php

/**
 * This is the model base class for the table "recepcionista".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Recepcionista".
 *
 * Columns in table "recepcionista" available as properties of the model,
 * followed by relations of table "recepcionista" available as properties of the model.
 *
 * @property integer $id_recepcionista
 * @property integer $id_pessoa
 * @property string $data_criaca
 *
 * @property Pessoa $idPessoa
 */
abstract class BaseRecepcionista extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'recepcionista';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Recepcionista|Recepcionistas', $n);
	}

	public static function representingColumn() {
		return 'data_criaca';
	}

	public function rules() {
		return array(
			array('id_pessoa, data_criaca', 'required'),
			array('id_pessoa', 'numerical', 'integerOnly'=>true),
			array('id_recepcionista, id_pessoa, data_criaca', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idPessoa' => array(self::BELONGS_TO, 'Pessoa', 'id_pessoa'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_recepcionista' => Yii::t('app', 'Id Recepcionista'),
			'id_pessoa' => null,
			'data_criaca' => Yii::t('app', 'Data Criaca'),
			'idPessoa' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_recepcionista', $this->id_recepcionista);
		$criteria->compare('id_pessoa', $this->id_pessoa);
		$criteria->compare('data_criaca', $this->data_criaca, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}