<?php

/**
 * This is the model base class for the table "tipo_pagamento".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TipoPagamento".
 *
 * Columns in table "tipo_pagamento" available as properties of the model,
 * followed by relations of table "tipo_pagamento" available as properties of the model.
 *
 * @property integer $id_tipo
 * @property string $nome
 *
 * @property Pagamento[] $pagamentos
 */
abstract class BaseTipoPagamento extends GxActiveRecord {

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'tipo_pagamento';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'TipoPagamento|TipoPagamentos', $n);
    }

    public static function representingColumn() {
        return 'nome';
    }

    public function rules() {
        return array(
            array('nome', 'required'),
            array('nome', 'length', 'max' => 45),
            array('id_tipo, nome', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
            'pagamentos' => array(self::HAS_MANY, 'Pagamento', 'id_tipo_pagamento'),
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'id_tipo' => Yii::t('app', 'Id Tipo'),
            'nome' => Yii::t('app', 'Nome'),
            'pagamentos' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_tipo', $this->id_tipo);
        $criteria->compare('nome', $this->nome, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

}
