<?php

/**
 * This is the model base class for the table "receita".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Receita".
 *
 * Columns in table "receita" available as properties of the model,
 * followed by relations of table "receita" available as properties of the model.
 *
 * @property integer $id_receita
 * @property integer $id_consulta
 * @property string $receita
 *
 * @property Consulta $idConsulta
 */
abstract class BaseReceita extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'receita';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Receita|Receitas', $n);
	}

	public static function representingColumn() {
		return 'receita';
	}

	public function rules() {
		return array(
			array('id_consulta, receita', 'required'),
			array('id_consulta', 'numerical', 'integerOnly'=>true),
			array('id_receita, id_consulta, receita', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idConsulta' => array(self::BELONGS_TO, 'Consulta', 'id_consulta'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_receita' => Yii::t('app', 'Id Receita'),
			'id_consulta' => null,
			'receita' => Yii::t('app', 'Receita'),
			'idConsulta' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_receita', $this->id_receita);
		$criteria->compare('id_consulta', $this->id_consulta);
		$criteria->compare('receita', $this->receita, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}