<?php

/**
 * This is the model base class for the table "recepcionista".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Recepcionista".
 *
 * Columns in table "recepcionista" available as properties of the model,
 * followed by relations of table "recepcionista" available as properties of the model.
 *
 * @property integer $id_recepcionista
 * @property integer $id_pessoa
 * @property string $data_criacao
 *
 * @property Pessoa $idPessoa
 */
abstract class BaseRecepcionista extends GxActiveRecord {

    public $nome_recepcionista;

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'recepcionista';
    }

    public static function label($n = 1) {
        return Yii::t('app', 'Recepcionista|Recepcionistas', $n);
    }

    public static function representingColumn() {
        return 'idPessoa';
    }

    public function rules() {
        return array(
            array('id_pessoa, data_criacao', 'required'),
            array('id_pessoa', 'numerical', 'integerOnly' => true),
            array('id_recepcionista, id_pessoa, data_criacao, nome_recepcionista', 'safe', 'on' => 'search'),
        );
    }

    public function relations() {
        return array(
            'idPessoa' => array(self::BELONGS_TO, 'Pessoa', 'id_pessoa'),
        );
    }

    public function pivotModels() {
        return array(
        );
    }

    public function attributeLabels() {
        return array(
            'id_recepcionista' => Yii::t('app', 'Id Recepcionista'),
            'id_pessoa' => null,
            'data_criacao' => Yii::t('app', 'Data Criacao'),
            'idPessoa' => null,
            'nome_recepcionista' => Yii::t('app', 'Recepcionista'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->with = array('idPessoa');

        $criteria->compare('id_recepcionista', $this->id_recepcionista);
        $criteria->compare('id_pessoa', $this->id_pessoa);
        $criteria->compare('data_criacao', $this->data_criacao, true);
        $criteria->compare('idPessoa.nome', $this->nome_recepcionista, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function afterFind() {
        $this->nome_recepcionista = isset($this->idPessoa->nome) ? $this->idPessoa->nome : '';

        parent::afterFind();
    }

}