<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array(
    'Profile Extensions' => 'Perfil',
    'Email Customization' => 'Personalizar a mensagem do email',
    'What\'s new?' => 'Qual a novidade?',
    'no tooltip provided' => 'nehuma dica foi disponibilizada',
    'A problem occurred during the Data and Access Permission saving action' => 'Um problema ocorreu durante o salvamento das permiss~oes de Dados e Acessos',
    'A problem occurred during the configuration saving action' => 'Um problema ocorreu durante o salvamento da configuração',
    'A problem occurred during the cron jobs configuration saving action' => 'Um problema ocorreu durante o salvamento da configuração das tarefas do Cron',
    'About the author' => '_',
    'Ban Period' => 'Periodo de bloqueio',
    'Ban Reason' => 'Motivo do bloqueio',
    'Controller' => 'Controladores',
    'Cron Jobs' => 'Cron Jobs',
    'Cron Jobs Configurations Saved' => 'Salvar a configuração das tarefas do Cron',
    'Cron Jobs succefully removed' => 'Tarefas do cron removidas com sucesso',
    'Data and Access Permission of <i>{displayname} group</i> changed' => 'Dados e Permissão de acesso do  <i>grupo {displayname}</i> mudou',
    'Data and Access Permission of <i>{displayname} user</i> changed' => 'Dados e Permissão de acesso do <i>usuário {displayname}</i> mudou',
    'Description' => 'Descrição',
    'Do you really want to approve {who} registration?' => 'Você autoriza o registro de {who}?',
    'Do you really want to ban {who}?' => 'Você quer bloquear o usuário {who}?',
    'Do you really want to delete the group {group}?' => 'Você que deletar o {group}?',
    'Do you really want to delete the user {user}?' => 'Você que deletar o usuário {user}?',
    'Do you really want to remove those CronJobs?' => 'Você quer remover essa tarefa do cron?',
    'Documentation' => 'Documentação',
    'Element' => 'Elemento',
    'First Steps' => 'Primeiros passos',
    'Forever' => 'Para sempre',
    'Group Home: {home}' => 'Nome do Grupo: {home}',
    'Group {groupname}: Data and Access Permissions' => ' Grupo {groupname}: Dados e Permissão de Acesso',
    'Impossible to delete the requested user/group. An Error Occurred' => 'Impossível remover este grupo/usuário. Um erro ocorreu',
    'Invalid Request.' => 'Requisição Inválida',
    'Is this thing safe?' => 'É seguro?',
    'Lapse' => 'Volta',
    'Last Execution' => 'Última execução',
    'License' => 'Licença',
    'Localization' => 'Localização',
    'Main Configurations' => 'Configuração Principal',
    'Module' => 'Módulo',
    'New Configurations Saved' => 'Salva Configuração',
    'New Group: Data and Access Permissions' => 'Novo Grupo: Dados e Permissão de Acesso',
    'New User: Data and Access Permissions' => 'Novo Usuário: Dados e Permissão de Acesso',
    'New group Created.' => 'Criado novo Grupo',
    'New user Created.' => 'Criado novo Usuário',
    'Options' => 'Opções',
    'Permission' => 'Permissão',
    'Permission granted from Group' => 'Permissão dada ao Grupo',
    'Remember if you delete a Group you\'ll delete all the users that belongs to it.' => 'Lembre-se que ao remover um grupo, você irá remover todos os usuários pertencentes a este grupo.',
    'Remove not installed CronJobs' => 'Remover tarefas do Cron não instaladas',
    'Root Tools' => 'Administração de Usuários',
    'Setting' => 'Configurar',
    'Setup the new accessControlFilter' => 'Configurar um novo accessControlFilter',
    'Status' => 'Status',
    'The following problems occurred: {errors}' => 'Ocorreu o seguinte problema: {errors}',
    'The requested cron does not exist.' => 'A tarefa do Cron solicitada não existe',
    'The requested rule does not exist.' => 'A regra solicitada não existe',
    'The requested user/group does not exist and cannot be deleted.' => 'A solicitação do usuário/grupo nao existe e pode ter sido removida.',
    'This group does not exist' => 'Este grupo não existe',
    'User {username}: Data and Access Permissions' => 'Usuário {username}: Dados e Permisssão de Acesso',
    'Using the new Access Rules' => 'Usando as novas regras de acesso',
    'Value' => 'Valor',
    'What\'s coming next?' => 'O que esta por vir?',
    'You are not allowed to change any configuration' => 'Você não está autorizado a alterar qualquer autorização',
    'You are not allowed to change the cron jobs configuration' => 'Você não está autorizado a alterar a configuração de tarefas do cron',
    'You are not allowed to remove cron jobs' => 'Você não está autorizado a remover as tarefas do cron',
    'You cannot assign to a User a Group that has a Level equal or higher then the one you belong to' => 'Você não pode se associar a um grupo que tenha um nível igual ou maior do qual voc^pertence',
    'You cannot ban a user with a level higher then yours.' => 'Você não pode bloquear um usuário com nível maior que o seu',
    'You cannot change constant values' => 'Você não pode mudar valores constantes',
    'You cannot change data or permissions of Root' => 'Você não pode mudar dados ou permissão do Root',
    'You cannot change data or permissions of a user or a group with a level higher then yours' => 'Você não pode mudar dados ou permissão de um usuário ou grupo com um nível de acesso maior que o seu',
    'You cannot change the Access Permission of the Root User' => 'Você não pode alterar a permissão de acesso do usuário root',
    'You cannot create a new user or group' => 'Você não pode criar um novo usuário ou grupo',
    'You cannot delete a user/group with an higher level then yours.' => 'Você não pode excluir um usuário / grupo com um nível superior ao seu.',
    'You cannot set a Group Level equal or higher then Root' => ' Você não pode definir um nível igual ou maior do que o Root',
    'You cannot set a Group Level equal or superior to your own' => 'Você não pode definir um nível igual ou superior ao seu',
    'You cannot set this value to a level equal or higher then your own' => 'Você não pode definir esse valor para um nível igual ou superior ao seu',
    'You didn\'t supply a valid id' => 'O ID você solicitou não é válido',
    'You don\'t have the permissions to delete any user/group' => 'Você não tem o permissão de excluir qualquer usuário / grupo',
    'add group' => ' Adicionar grupo',
    'add user' => 'Adicionar um usuário',
    'if you omit the password a random one will be generated' => ' Se você não especificar uma senha ela será gerada aleatoriamente',
    'if you omit the username the user will be able to chose one when he activates the account' => 'Se você não especificar um login (username) será solicitado ao usuário fornecer um durante o registo',
    'invalid value' => 'valor inválido',
    '{class}.allowAutoLogin must be set true in order to use cookie-based authentication.' => '{class}.allowAutoLogin deve ser definido como true para habilitar um cookie de autenticação.',
    '{n} Day|{n} Days' => '{n} Dia|{n} Dias',
    '{n} Month|{n} Months' => '{n} Mês|{n} Meses',
    '{n} Week|{n} Weeks' => '{n} Semana|{n} Semanas',
    '{username}\'s account is banned untill {day}.' => '{username} foi bloquado até o dia {day}',
    '{username}\'s account is now active.' => 'A conta {username} está ativa',
    '{what} deleted.' => '{what} removido.',
    'if you omit the username the user will be able to chose one upon activation of the account' => 'Se você omitir o nome do usuário será capaz de escolher um após a ativação da conta'
);
