<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array(
    0 => '',
    'allow everyone, even guests, to see user profiles' => 'Permitir que qualquer pessoa, até os clientes possam ver os perfis dos usuário',
    'allow user registration' => 'Permitir o registro do usuário ',
    'if a user has on a controller admin permissions will have access to write and read pages. If he has write permissions will also have access to read pages' => 'Se um usuário tiver permissões de administrador ele terá permissão para ler e escrever registros. Se ele tem permissão de escrita também poderá ler registros',
    'if true users just have to provide user and email to reset their password.<br/>Otherwise they will have to answer their custom question' => 'se verdadeiro, os usuários devem login e e-mail para redefinir sua senha. <br/> Caso contrário, eles terão que responder a sua pergunta personalizada',
    'if true when a user creates an account a mail with an activation code will be sent to his email address' => 'se verdadeiro o usuário irá criar sua conta e posteriormente receberá um e-mail com o código de ativação',
    'if true when a user creates an account a user with user admin rights will have to approve the registration.<br/>If both this setting and user_need_activation are true the user will need to activate is account first and then will need the approval' => 'se verdadeiro, o usuário irá criar sua conta, porém um usuário com direitos de administrador terá de aprovar o cadastro. <br/> Se forem marcadas esta opção e a opção que o usuário necessita ativação, o usuário precisa ativar a sua conta e depois aguardar a da aprovação.',
    'logged user can see other users profiles' => 'usuários que fizeram login podem ver outros perfis',
    'logged users can see the complete user list' => 'usuários que fizeram login podem ver a lista completa de usuários',
    'password strength:<br/>weak: password of at least 5 characters, any character allowed.<br/>
			medium: password of at least 5 characters, must contain at least 2 digits and 2 letters.<br/>
			strong: password of at least 5 characters, must contain at least 2 digits, 2 letters and a special character.' => 'Dificuldade da senha:<br/>fraca: senha com pelo menos 5 caracteres, e qualquer caracter é permitido.<br/>
  			média: senha com ao menos 5 caracteres, deve conter pelo menos 2 números e 2 letras.<br/>
  			forte: senha com pelo menos 5 caracteres, deve conter pelo menos 2 números, duas letras e um caracter especial',
    'the group new users automatically belong to' => 'o grupo de novos usuários automaticamente pertence a ',
    'userGroups version' => 'versão do userGroups',
    'users can set their own home' => 'usuários podem confirgurar a sua prória página inicial',
    'users with just admin write permissions won\'t see the Main Configuration and Cron Jobs panels' => 'Usuários com permissões apenas de escrita (write) no admin não vão ver a Configuração Principal e o Cron Jobs',
    'users with userGroups admin admin permission will have access to everything, just like root' => 'usuários com permisssão de amdinistrador terão acesso a todos os módulos, igual ao root',
    'if true crons must be executed from the server using a crontab' => 'Se verdadeiro, crons deve ser executado a partir do servidor usando um crontab',
);
