<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array(
    'Cronjob not installed' => 'Tarefas do Cron não instaladas',
    'No description found for the requested cron job' => 'Nemhuma descrição foi encontrada para a requisição da tarefa do Cron',
    'You didn\'t set the cron table name' => 'Você não configurou um nome para a tarefa do Cron',
    'You have to provide a name for the cronjob' => 'Você deve fornecer um nome a tarefa do Cron',
    'could not install the module. Lapse must be an integer' => 'Não pode instalar este módulo. O intervalo de tempo tem que ser maior',
    'delete users who have not been activated for more then 7 days' => 'Cancela usuários que não foram ativados em 7 dias',
    'installed and running' => 'Instalado e funcionando',
    'not installed' => 'Não instalado',
    'reactivate users whose ban period is over' => 'Reativar usuários que passaram pelo período de bloquados',
    'the model provided is not an instance of CActiveRecord' => 'o modelo fornecido não é uma instancia do CActiveRecord',
    'the provided criteria are not an instance of CDbCriteria' => 'o critério fornecido não é uma instancia do CDbCriteria',
    'you didn\'t initialize che UGCron singleton' => 'voce não inicializou o UGCron',
    'you didn\'t provide a valid action' => 'você não forneceu uma ação válida',
    'you didn\'t set the columns to update' => 'você nao configurou as colunas para atualização',
);
