<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array(
    'General Info' => 'Informação Geral ',
    'Security' => 'Segurança',
    'Fields with {*} are required.' => 'Os campos com {*} são necessários.',
    'Remember Me' => 'Permanecer logado',
    'A password change has been requested.<br/>You won\'t be able to login until you change the password.' => 'A alteração de senha foi solicitada. <br/>Você não pode fazer o login até que você altere a senha.',
    'Access' => 'Acesso',
    'Account not active' => 'A conta não ativa',
    'Activate the account' => 'Ativar a conta',
    'An Error Occurred. Please try later.' => 'Houve um erro tente novamente mais tarde.',
    'An email was sent with the instructions to activate your account to the address {email}.' => 'Um e-mail com detalhes para ativar a sua conta foi enviado para{email} ',
    'Approve Registration' => 'Aprovar o registo',
    'Ban User' => 'Banir usuário',
    'Change Password' => 'Trocar a senha',
    'Confirm Password' => 'Confirmar senha',
    'Data Updated Succefully' => 'Dados atualizados com sucesso',
    'Delete' => 'Apagar',
    'Documentation' => 'Documentação',
    'Edit Profile' => 'Editar perfil',
    'Edit {username}\'s Profile' => 'Editar perfil de {username} ',
    'Email' => 'Email',
    'Group' => 'Grupo',
    'Group Level' => 'Nível do Grupo',
    'Group Name' => 'Nome do Grupo',
    'Groups' => 'Grupos',
    'Home' => 'Página Inicial',
    'Impossible send email to the address {mail}' => 'Não foi possível enviar um e-mail para {email}',
    'Invalid email address' => 'Endereço de e-mail inválido',
    'Invite User' => 'Convidar usuário',
    'Reinvite User' => 'Reconvidar usuário',
    'Level' => 'Nível',
    'Login Required' => 'Login necessário',
    'My Profile' => 'Meu perfil',
    'Name' => 'Nome',
    'Old Password' => 'Senha antiga',
    'Password' => 'Senha',
    'Password Reset' => 'Reinicializar Senha',
    'Password Reset: Answer' => 'Reinicializar senha:Resposta',
    'Password Reset: Question' => 'Reinicializar senha:Pergunta',
    'Please enter the letters as they are shown in the image above.<br/>Letters are not case-sensitive.' => 'Por favro entre com as letras que estão sendo mostradas na imagem abaixo.<br/>Não há diferença entre letras maúsculas e minúsculas',
    'Proceed' => 'Continuar',
    'Recovery Mode' => 'Modo de recuperação',
    'Register' => 'Registre',
    'Registration Complete, you can now login.' => 'Registo completo você pode fazer login',
    'Registration Complete. You now have to wait for an admin to approve your account.' => 'Registro Completo. Você vai ter que esperar até que um administrador aprove a sua conta. ',
    'Request New Password' => 'Pedir uma nova senha',
    'Resend Email' => 'Reenviar e-mail',
    'Root Tools' => 'Ferramentas',
    'Salt' => 'Salt',
    'Save' => 'Salvar',
    'The requested page does not exist.' => 'A página solicitada não existe.',
    'The {messageType} Mail was succefully sent to {mail}' => 'O e-mail {messageType} foi enviada para {email}',
    'This account is not approved yet' => 'Esta conta ainda não foi aprovada',
    'Update' => 'Atualizar',
    'Update User' => 'Atualizar o usuário',
    'Update User Profile' => 'Atualizar o perfil de usuário ',
    'User Invitation' => 'Convidar usuário',
    'User List' => 'Lista de usuários',
    'Users List' => 'Lista de usuários',
    'User Name' => 'Nome do usuário',
    'Group Name' => 'Grupo',
    'Group name' => 'Grupo',
    'User Registration' => 'Registro de Usuário',
    'Username' => 'Nome do usuário',
    'Users' => 'Usuários',
    'Verification Code' => 'Código de Verificação',
    'We are sorry, but your account is banned' => 'Desculpe sua conta foi bloqueada',
    'You are not allowed to update other accounts' => 'Você não tem permissão para alterar outras contas',
    'You didn\'t enter the correct password' => 'Você não digitou a senha correta',
    'You have succefully invited {email} to join {website}.' => 'Você acaba de convidar o {email} a participar do {website}',
    'profile' => 'Perfil',
    'register' => 'Registro',
    'the confirmation password doesn\'t match the password' => 'senha não coincide com a senha de confirmação',
    'username must be at least 4 characters and can only be alphanumeric' => 'Nomes de usuário devem ter no mínimo 4 caracteres e só pode ser alfanumérico',
    '{username}\'s Profile' => 'Perfil {username} ',
    'Root password must contain at least 2 digits and 2 letters and have at least 5 characters' => 'senha do root deve conter pelo menos duas letras e dois números',
    'the password must be of at least 5 characters' => 'senha deve ter pelo menos 5 caracteres',
    'the password must contain at least 2 digits and 2 letters and have at least 5 characters' => 'senha deve conter pelo menos 2números e 2 letras e pelo menos 5 caracteres',
    'the password must contain at least 2 digits, 2 letters and a special character' => 'senha deve conter pelo menos 2números e 2 letras e pelo um caracter especial',
    'You may optionally enter a comparison operator' => 'Você pode, opcionalmente, digitar um operador de comparação',
    'at the beginning of each of your search values to specify how the comparison should be done' => 'no início de cada pesquisa de valores para especificar a forma como a comparação deve ser feita',
    'An email containing the instructions to reset your password has been sent to your email address: {email}' => 'Um email contendo as instruções para redefinir sua senha foi enviada para o seu e-mail: {email}'
);
