<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array(
    'To Activate your account please click on this link:<br/>{full_link}<br/>or you can go to this address<br/>{link}<br/>and insert in the form the following data<br/>username: <b>{username}</b><br/>activation code: <b>{activation_code}</b><br/>' => 'Para ativar sua conta, clique neste link: <br/>{full_link}<br/> ou você pode ir para este endereço <br/>{link} e preencher o formulário<br/><br/>usuário <b>{username}</b><br/>código de ativação: <b>{activation_code}</b><br/>',
    'You have been invited to join {website}.<br/>To reactivate your account and set the new password please click on this link:<br/>{full_link}<br/>or you can go to this address<br/>{link}<br/>and insert in the form the following data<br/><br/>username: <b>{username}</b><br/>activation code: <b>{activation_code}</b><br/><br/>You will be able to change the username when you activate the account' => 'Você foi convidado para acessar o sistema {website}. <br/>Para reativar sua conta e definir a nova senha por favor clique neste link: <br/> {full_link}<br/> ou você pode ir para este endereço <br/> {link} <br/> e preencher no formulário os seguintes dados <br/><br/> usuário: <b> {username} </ b><br/> código de ativação: <b> {activation_code} </ b> <br/><br/>Você será capaz de mudar o nome de usuário quando você ativar a conta',
    'You requested a password reset.<br/> Your account will be disabled until you set a new password.<br/> To reactivate your account and set the new password please click on this link:<br/>{full_link} <br/>or you can go to this address<br/>{link}<br/>and insert in the form the following data<br/>username: <b>{username}</b> <br/>activation code: <b>{activation_code}</b><br/>' => 'Você solicitou a troca de senha.<br/>Sua conta será desativada até que você defina uma nova senha.<br/>Para reativar sua conta e definir a nova senha por favor clique neste link::<br/>{full_link}<br/>ou você pode ir a este endereço<br/>{link}<br/>e insira no formulário os seguintes dados<br/><br/>nome de usuário: <b>{username}</b><br/>código de ativação: <b>{activation_code}</b><br/>',
    'account activation' => 'Ativação da conta.',
    'invitation to {website}' => 'Convite para {website}.',
    'password reset request' => 'Solicitação de troca de senha.',
);
