<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array(
    'A mail to reset your password was sent to the address {email}.' => 'Um email com as instruções de como reinicializar a senha foi enviado para o endereço {email}',
    'Input the right answer' => 'Entre com a resposta correta',
    'Invalid activation code' => 'Código de ativação não é válido',
    'Invalid email address' => 'Email não é válido',
    'Password Recovery' => 'Recuperar senha',
    'This user cannot log in recovery mode.' => 'Este usuário não pode se logar no modo de recuperação',
    'User Activation' => 'Ativação do Usuário',
    'Username not valid' => 'Usuário não é valido',
    'Email not valid' => 'Email não é valido',
    'wrong user or password.' => 'Usuário ou senha inválidos',
    'You was logged, but to recovery another account, you have been log out.' => 'Você estava logado,mas para recuperar outra conta, você foi deslogado',
);
